# Generated by Django 5.0.3 on 2024-04-02 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1000 TO 5000', '1000 TO 5000'), ('5000 TO 10000', '5000 TO 10000'), ('10000 TO 20000', '10000 TO 20000'), ('20000 TO 50000', '20000 TO 50000'), ('50000 TO 100000', '50000 TO 100000'), ('100000 TO 500000', '100000 TO 500000'), ('500000 TO 1000000', '500000 TO 1000000'), ('1000000 TO 5000000', '1000000 TO 5000000'), ('5000000 TO 10000000', '5000000 TO 10000000'), ('10000000 TO 50000000', '10000000 TO 50000000'), ('50000000 TO 100000000', '50000000 TO 100000000'), ('100000000 TO 500000000', '100000000 TO 500000000'), ('500000000 TO 1000000000', '500000000 TO 1000000000'), ('1000000000 TO 5000000000', '1000000000 TO 5000000000')], max_length=100)),
            ],
        ),
    ]
