# Generated by Django 5.0.3 on 2024-04-02 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batirem', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='filter_price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='batirem.filter_price'),
            preserve_default=False,
        ),
    ]
